[package]
name = "iot_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
rand = "0.8.5"
ratatui = "0.30.0"
thiserror = "2.0.18"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }

iot_sdk = { git = "https://github.com/oac1771/iot_sdk", tag = "0.0.0-rc0" }