[package]
name = "iot_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures-util = "0.3.32"
futures = "0.3.32"
ratatui = "0.30.0"
thiserror = "2.0.18"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }

iot_sdk = { path = "../iot_sdk" }
# iot_sdk = { git = "https://github.com/oac1771/iot_sdk", tag = "0.0.0-rc0" }

color-eyre = "0.6"
